name: Build HiGHS

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-12, macos-14]

    steps:
    - name: Checkout HiGHS
      uses: actions/checkout@v4
      with:
        repository: 'ERGO-Code/HiGHS'
        ref: 'v1.7.0'

    - name: Build HiGHS
      run: |
        mkdir build
        cmake -S. -Bbuild -DFAST_BUILD=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install
        cmake --build build --config Release --parallel 6

    - name: Install HiGHS
      run: |
        cmake --install build

    - name: patch rpath on linux
      if: runner.os == 'Linux'
      run: |
        patchelf --set-rpath '$ORIGIN/../lib' install/bin/highs

    - name: patch rpath on macos
      if: runner.os == 'macOS'
      run: |
        install_name_tool -add_rpath '@loader_path/../lib' install/bin/highs

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: highs-artifact-${{ runner.os }}-${{ runner.arch }}
        path: install/

  # I want to create a release, download the artifacts and upload them to release
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        pattern: highs-artifact-*
        path: artifacts
    - name: Display structure of downloaded files
      run: ls artifacts
    - name: Create archives
      run: |
        cd artifacts
        for f in *; do
          if [ -d "$f" ]; then
            zip -r "$f.zip" "$f"
          fi
        done
    - name: Display structure of archives
      run: ls artifacts
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          artifacts/*.zip
        prerelease: true
    
