name: Build HiGHS

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout HiGHS
      uses: actions/checkout@v2
      with:
        repository: 'ERGO-Code/HiGHS'
        ref: 'v1.6.0'

    - name: Build HiGHS
      run: |
        mkdir build
        cd build
        cmake .. -DFAST_BUILD=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Install HiGHS
      run: |
        cd build
        cmake --install .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: installed-directory-${{ matrix.os }}
        path: build/install/