name: Build HiGHS

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest, macos-14]

    steps:
    - name: Checkout HiGHS
      uses: actions/checkout@v4
      with:
        repository: 'ERGO-Code/HiGHS'
        ref: 'v1.6.0'

    - name: Build HiGHS
      run: |
        mkdir build
        cmake -S. -Bbuild -DFAST_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install
        cmake --build build --config Release --parallel 6

    - name: Install HiGHS
      run: |
        cmake --install build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: highs-artifact-${{ matrix.os }}
        path: install/